#include: package:flutter_lints/flutter.yaml
#
#linter:
#  rules:



# ----------------------------------------------------------------------------
# 替换为下面代码，使用 test_lint_plugin
include: package:pedantic/analysis_options.yaml

analyzer:
  plugins:
    - test_lint_plugin

  exclude:
    - dx/**
    - tiny/**