name: fluttersample
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2  #ios Icons
  cached_network_image: ^3.0.0-nullsafety
  fluttertoast: ^8.0.7
  flutter_easyloading: ^3.0.3
  event_bus: 2.0.0
  http: 0.13.3
  dio: 4.0.0
  http2: 1.0.1
  json_annotation: 4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: 2.1.1
  json_serializable: 5.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/img/